spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.8.151:3306/file
    username: root
    password: 657431zhurui
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 1002048MB
      max-request-size: 1002048MB
  #关闭缓存
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #关闭缓存
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
server:
  port: 2233
